begin;
alter table public.teams add column active boolean not null default true,
 add column version integer not null default 0,
 add column created_at timestamptz not null default now();
alter table public.teams alter column id add generated by default as identity;
select setval(pg_get_serial_sequence('public.teams','id'),(select max(id) from public.teams));
alter table public.teams drop constraint teams_name_key;
create unique index teams_company_normalized_name on public.teams(company_id,lower(regexp_replace(btrim(name),'\s+',' ','g')));
create table public.team_events (
 request_id uuid primary key,
 team_id integer not null references public.teams(id),
 occurred_at timestamptz not null default now(),
 before_data jsonb,
 after_data jsonb not null
);
alter table public.team_events enable row level security;
revoke all on public.team_events from anon,authenticated;
grant select on public.team_events to anon,authenticated;
create policy public_read on public.team_events for select to anon,authenticated using(true);

create function public.save_team(p_request_id uuid,p_id integer,p_company_id text,p_name text,p_kind text,p_active boolean,p_expected_version integer)
returns public.teams language plpgsql security definer set search_path='' as $$
declare item public.teams; previous public.teams; old public.team_events; normalized text;
begin
 normalized:=regexp_replace(btrim(p_name),'\s+',' ','g');
 if p_request_id is null or p_company_id is null or p_company_id not in ('RALT','JVP','DSX','ENGELMIG')
 or normalized is null or length(normalized) not between 1 and 100
 or p_kind is null or p_kind not in ('PESADA','LINHA VIVA','LIMPEZA DE FAIXA','RECOLHIMENTO DE PODA','OUTRO','TIPO NÃO INFORMADO')
 or p_active is null or p_expected_version is null or p_expected_version<0 then raise exception 'INVALID_TEAM'; end if;
 -- Serializes retries of the same request, including team creation.
 perform pg_advisory_xact_lock(hashtextextended(p_request_id::text,0));
 select * into old from public.team_events where request_id=p_request_id;
 if found then
  if (p_id is not null and old.team_id<>p_id) or old.after_data->>'company_id'<>p_company_id or old.after_data->>'name'<>normalized or old.after_data->>'kind'<>p_kind or (old.after_data->>'active')::boolean<>p_active then raise exception 'INVALID_REQUEST_ID'; end if;
  select * into item from public.teams where id=old.team_id;return item;
 end if;
 if p_id is null then
  if not p_active or p_expected_version<>0 or p_kind='TIPO NÃO INFORMADO' then raise exception 'INVALID_TEAM'; end if;
  insert into public.teams(company_id,name,kind) values(p_company_id,normalized,p_kind) returning * into item;
 else
  select * into previous from public.teams where id=p_id for update;
  if not found then raise exception 'TEAM_NOT_FOUND'; end if;
  if previous.version<>p_expected_version then raise exception 'STALE_TEAM'; end if;
  update public.teams set company_id=p_company_id,name=normalized,kind=p_kind,active=p_active,version=version+1 where id=p_id returning * into item;
 end if;
 insert into public.team_events(request_id,team_id,before_data,after_data) values(p_request_id,item.id,case when p_id is null then null else to_jsonb(previous) end,to_jsonb(item));
 return item;
exception when unique_violation then raise exception 'DUPLICATE_TEAM';
end;
$$;
revoke all on function public.save_team(uuid,integer,text,text,text,boolean,integer) from public,anon,authenticated;
grant execute on function public.save_team(uuid,integer,text,text,text,boolean,integer) to anon,authenticated;
-- Keep existing RPC and cycle semantics; reject new work on inactive teams.
create function public.require_active_team() returns trigger language plpgsql set search_path='' as $$
begin
 if not exists(select 1 from public.teams where id=new.team_id and active) then raise exception 'TEAM_INACTIVE'; end if;
 return new;
end;
$$;
create trigger inspections_active_team before insert or update on public.inspections for each row when (new.inspected_at is not null) execute function public.require_active_team();
create trigger non_conformities_active_team before insert on public.non_conformities for each row execute function public.require_active_team();
alter publication supabase_realtime add table public.teams;
commit;
